### PR TITLE
Wrap package install in quotes to get around the interpolation problem

### PR DESCRIPTION
**Pull request by bbriggs**
GPU build is failing because the exeuction environment for GH Actions apparently doesn't like the `${CUDA/./-}` syntax to format a variable. This PR massages the commands to get it to build.

### CODE REVIEW

**Review by tushar-parekh — APPROVED** [review]

**Review by joshuacook — APPROVED** [review]

**Comment by joshuacook** [comment]
Did we resolve the too large layers issue? @bbriggs

**Comment by bbriggs** [comment]
> Did we resolve the too large layers issue? @bbriggs

Not yet. Not sure when I'll have bandwidth to look at this issue again. Maybe @tushar-parekh has some cycles soon?

**Comment by tushar-parekh** [comment]
hello,

i can take ownership of this issue

@Joshua Cook ***@***.***> please create/assign ticket to me
this sprint

regards,
Tushar Parekh
DevSecOps Engineer, Data Engineer // Hypergiant Industries
Hypergiant.com <http://hypergiant.com/> // Tomorrowing Today™
1-647-785-7878

**Comment by craigjmidwinter** [comment]
Going to close this as @tushar-parekh has a ticket to implement a new build strategy for our images (https://gohypergiant.atlassian.net/browse/MLSDK-284)

**Pull request closed without merging**
