### PR TITLE
MLSDK-407: HyperPack | Resolve src package bloat & make module import independent of dir location

### PR DESCRIPTION
**Pull request by johnhouhyper**
JIRA TICKET
[MLSDK-407](https://gohypergiant.atlassian.net/browse/MLSDK-407)

CHANGE SUMMARY
1. Instruct user to `pip install` the `hyperpackage` as a regular install, and not an editable one, by omitting the `-e` flag. Doing this removes the creation of a `src` folder. Previously, this `src` folder creation limited the user from importing `hyperpackage` in a different directory than the one in which the `pip install` command was called. Furthermore, exposing the user to the `src` folder, with all the other `hyperdrive` components, was unnecessary and made things look bloated.
2. Fix `hyperpackage` code so that downstream import errors (e.g., `hyperpackage.flavor.pytorch`) don't occur in the absence of a `src` folder.

MOTIVATION/CONTEXT
Make importing/usage of `hyperpackage` more flexible and user-friendly.

### CODE REVIEW

**Comment by johnhouhyper** [comment]
Pinging @godsylla and @scotttarlow for visibility.

**Review by craigjmidwinter — APPROVED** [review]

**Review by godsylla — CHANGES_REQUESTED** [review]
Only a subset of the necessary files are coming over from the `hyperdrive/hyperpackage` directory and not all the necessary ones in this revision. see the JIRA ticket for more details

**Review by godsylla — APPROVED** [review]
Approved! It works in both cases (as magic in Jupyter notebook, and terminal) 
- it is captured in my package list when I print out installed packages from my environment.

**Comment by johnhouhyper** [comment]
> Only a subset of the necessary files are coming over from the `hyperdrive/hyperpackage` directory and not all the necessary ones in this revision. see the JIRA ticket for more details

The issue is that, for the review, we were still `pip install`-ing from the `stable` branch, and not the `MLSDK-407-rm-hyperpackage-bloat` branch, which is where the changes reside. Confirmed that `pip install`-ing from the `MLSDK-407-rm-hyperpackage-bloat` produces the desired results/output. Now that this PR has been approved, we can merge, and `pip install`-ing from `stable` will work as intended.

**Pull request merged**
